/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import modelo.*;

/**
 *
 * @author a22noellr
 */
public class MenuPrincipal extends javax.swing.JFrame {
    //ATRIBUTOS
    private ArrayList<Alumno> listaAlumnos = new ArrayList();
    private ArrayList<Modulo> listaModulos = new ArrayList();
    private DefaultListModel modelListaModAlum=new DefaultListModel();
    private File txtAlumnos=new File("alumnos.txt");
    private File txtModulos=new File("modulos.txt");
    private ObjectOutputStream outGuardar;
    private ObjectInputStream inCargar;

    /**
     * Creates new form Menu
     */
    public MenuPrincipal() {
        initComponents();
        try{
            if(!txtAlumnos.exists()){
            txtAlumnos.createNewFile();
            }
            if(!txtModulos.exists()){
                txtModulos.createNewFile();
            }
        }
        catch(IOException e){
            JOptionPane.showMessageDialog(this, "Error en el manejo de archivos.");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdAnadirModul = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        lblAltaModul = new javax.swing.JLabel();
        jpAnadirMod = new javax.swing.JPanel();
        lblNombreMod = new javax.swing.JLabel();
        lblHorasMod = new javax.swing.JLabel();
        lblUnidadesMod = new javax.swing.JLabel();
        txtNombreMod = new javax.swing.JTextField();
        txtHorasMod = new javax.swing.JTextField();
        txtUnidadesMod = new javax.swing.JTextField();
        btnGrabarMod = new javax.swing.JButton();
        btnLimpiarMod = new javax.swing.JButton();
        jdAnadirAlum = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        btnGrabarAlum = new javax.swing.JButton();
        btnLimpiarAlum = new javax.swing.JButton();
        btnQuitarModAlum = new javax.swing.JButton();
        jcbModuls = new javax.swing.JComboBox<>();
        lblMatricMod = new javax.swing.JLabel();
        jpAnadirAlum = new javax.swing.JPanel();
        lblAnaNombreAlum = new javax.swing.JLabel();
        lblAnaLocalidadAlum = new javax.swing.JLabel();
        txtAnaNombreAlum = new javax.swing.JTextField();
        txtAnaLocalidadAlum = new javax.swing.JTextField();
        lblAltaAlum = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jlAnaModAlum = new javax.swing.JList<>();
        btnAnaModAlum = new javax.swing.JButton();
        jdVerAlum = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        lblVerModAlum = new javax.swing.JLabel();
        jpDatosAlum = new javax.swing.JPanel();
        lblVerNombreAlum = new javax.swing.JLabel();
        lblVerLocalidadAlum = new javax.swing.JLabel();
        txtVerNombreAlum = new javax.swing.JTextField();
        txtVerLocalidadAlum = new javax.swing.JTextField();
        lblVerHorasAlum = new javax.swing.JLabel();
        txtVerHorasAlum = new javax.swing.JTextField();
        lblNombreBuscarAlum = new javax.swing.JLabel();
        txtNombreAlumBuscar = new javax.swing.JTextField();
        btnMostrarAlum = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jlVerModAlum = new javax.swing.JList<>();
        jpPrincipal = new javax.swing.JPanel();
        btnAnadirAlum = new javax.swing.JButton();
        btnAnadirModul = new javax.swing.JButton();
        btnVerAlum = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmAlumnos = new javax.swing.JMenu();
        jmiAnadirAlum = new javax.swing.JMenuItem();
        jmiVerAlum = new javax.swing.JMenuItem();
        jmiGuardarAlum = new javax.swing.JMenuItem();
        jmiSalvarAlum = new javax.swing.JMenuItem();
        jmModulos = new javax.swing.JMenu();
        jmiAnadirModul = new javax.swing.JMenuItem();
        jmiGuardarModul = new javax.swing.JMenuItem();
        jmiSalvarModul = new javax.swing.JMenuItem();

        jdAnadirModul.setTitle("AcademiaMas");
        jdAnadirModul.setMaximumSize(new java.awt.Dimension(500, 500));
        jdAnadirModul.setMinimumSize(new java.awt.Dimension(500, 500));
        jdAnadirModul.setPreferredSize(new java.awt.Dimension(500, 500));

        jPanel1.setMaximumSize(new java.awt.Dimension(500, 500));
        jPanel1.setMinimumSize(new java.awt.Dimension(500, 500));
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 500));

        lblAltaModul.setText("ALTA MÓDULOS");
        lblAltaModul.setMaximumSize(new java.awt.Dimension(120, 30));
        lblAltaModul.setMinimumSize(new java.awt.Dimension(120, 30));
        lblAltaModul.setPreferredSize(new java.awt.Dimension(120, 30));

        jpAnadirMod.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 102, 255)), "Añadir Módulo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 0, 255))); // NOI18N
        jpAnadirMod.setToolTipText("");

        lblNombreMod.setText("Nombre:");
        lblNombreMod.setMaximumSize(new java.awt.Dimension(70, 20));
        lblNombreMod.setMinimumSize(new java.awt.Dimension(70, 20));
        lblNombreMod.setPreferredSize(new java.awt.Dimension(70, 20));

        lblHorasMod.setText("Horas:");
        lblHorasMod.setMaximumSize(new java.awt.Dimension(70, 20));
        lblHorasMod.setMinimumSize(new java.awt.Dimension(70, 20));
        lblHorasMod.setPreferredSize(new java.awt.Dimension(70, 20));

        lblUnidadesMod.setText("Unidades:");
        lblUnidadesMod.setMaximumSize(new java.awt.Dimension(70, 20));
        lblUnidadesMod.setMinimumSize(new java.awt.Dimension(70, 20));
        lblUnidadesMod.setPreferredSize(new java.awt.Dimension(70, 20));

        txtNombreMod.setMaximumSize(new java.awt.Dimension(150, 25));
        txtNombreMod.setMinimumSize(new java.awt.Dimension(150, 25));
        txtNombreMod.setPreferredSize(new java.awt.Dimension(150, 25));

        txtHorasMod.setMaximumSize(new java.awt.Dimension(150, 25));
        txtHorasMod.setMinimumSize(new java.awt.Dimension(150, 25));
        txtHorasMod.setPreferredSize(new java.awt.Dimension(150, 25));

        txtUnidadesMod.setMaximumSize(new java.awt.Dimension(150, 25));
        txtUnidadesMod.setMinimumSize(new java.awt.Dimension(150, 25));
        txtUnidadesMod.setPreferredSize(new java.awt.Dimension(150, 25));

        javax.swing.GroupLayout jpAnadirModLayout = new javax.swing.GroupLayout(jpAnadirMod);
        jpAnadirMod.setLayout(jpAnadirModLayout);
        jpAnadirModLayout.setHorizontalGroup(
            jpAnadirModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpAnadirModLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpAnadirModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpAnadirModLayout.createSequentialGroup()
                        .addComponent(lblNombreMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNombreMod, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE))
                    .addGroup(jpAnadirModLayout.createSequentialGroup()
                        .addComponent(lblHorasMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtHorasMod, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jpAnadirModLayout.createSequentialGroup()
                        .addComponent(lblUnidadesMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtUnidadesMod, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jpAnadirModLayout.setVerticalGroup(
            jpAnadirModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpAnadirModLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpAnadirModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombreMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpAnadirModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHorasMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHorasMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpAnadirModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUnidadesMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUnidadesMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        btnGrabarMod.setText("Grabar");
        btnGrabarMod.setMaximumSize(new java.awt.Dimension(80, 20));
        btnGrabarMod.setMinimumSize(new java.awt.Dimension(80, 20));
        btnGrabarMod.setPreferredSize(new java.awt.Dimension(80, 20));
        btnGrabarMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrabarModActionPerformed(evt);
            }
        });

        btnLimpiarMod.setText("Limpiar");
        btnLimpiarMod.setMaximumSize(new java.awt.Dimension(80, 20));
        btnLimpiarMod.setMinimumSize(new java.awt.Dimension(80, 20));
        btnLimpiarMod.setPreferredSize(new java.awt.Dimension(80, 20));
        btnLimpiarMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarModActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnGrabarMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLimpiarMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jpAnadirMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblAltaModul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(83, 83, 83)))
                .addContainerGap(225, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblAltaModul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpAnadirMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGrabarMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimpiarMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(238, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jdAnadirModulLayout = new javax.swing.GroupLayout(jdAnadirModul.getContentPane());
        jdAnadirModul.getContentPane().setLayout(jdAnadirModulLayout);
        jdAnadirModulLayout.setHorizontalGroup(
            jdAnadirModulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jdAnadirModulLayout.setVerticalGroup(
            jdAnadirModulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jdAnadirAlum.setTitle("AcademiaMas");
        jdAnadirAlum.setMaximumSize(new java.awt.Dimension(500, 500));
        jdAnadirAlum.setMinimumSize(new java.awt.Dimension(500, 500));
        jdAnadirAlum.setPreferredSize(new java.awt.Dimension(500, 500));

        jPanel2.setMaximumSize(new java.awt.Dimension(500, 500));
        jPanel2.setMinimumSize(new java.awt.Dimension(500, 500));
        jPanel2.setPreferredSize(new java.awt.Dimension(500, 500));

        btnGrabarAlum.setText("Grabar");
        btnGrabarAlum.setMaximumSize(new java.awt.Dimension(80, 20));
        btnGrabarAlum.setMinimumSize(new java.awt.Dimension(80, 20));
        btnGrabarAlum.setPreferredSize(new java.awt.Dimension(80, 20));
        btnGrabarAlum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrabarAlumActionPerformed(evt);
            }
        });

        btnLimpiarAlum.setText("Limpiar");
        btnLimpiarAlum.setMaximumSize(new java.awt.Dimension(80, 20));
        btnLimpiarAlum.setMinimumSize(new java.awt.Dimension(80, 20));
        btnLimpiarAlum.setPreferredSize(new java.awt.Dimension(80, 20));
        btnLimpiarAlum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarAlumActionPerformed(evt);
            }
        });

        btnQuitarModAlum.setText("Quitar");
        btnQuitarModAlum.setMaximumSize(new java.awt.Dimension(80, 20));
        btnQuitarModAlum.setMinimumSize(new java.awt.Dimension(80, 20));
        btnQuitarModAlum.setPreferredSize(new java.awt.Dimension(80, 20));
        btnQuitarModAlum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitarModAlumActionPerformed(evt);
            }
        });

        jcbModuls.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbModulsActionPerformed(evt);
            }
        });

        lblMatricMod.setText("Módulos:");
        lblMatricMod.setMaximumSize(new java.awt.Dimension(70, 20));
        lblMatricMod.setMinimumSize(new java.awt.Dimension(70, 20));
        lblMatricMod.setPreferredSize(new java.awt.Dimension(70, 20));

        jpAnadirAlum.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 102, 255)), "Añadir Alumno", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 0, 255))); // NOI18N
        jpAnadirAlum.setToolTipText("");

        lblAnaNombreAlum.setText("Nombre:");
        lblAnaNombreAlum.setMaximumSize(new java.awt.Dimension(70, 20));
        lblAnaNombreAlum.setMinimumSize(new java.awt.Dimension(70, 20));
        lblAnaNombreAlum.setPreferredSize(new java.awt.Dimension(70, 20));

        lblAnaLocalidadAlum.setText("Localidad:");
        lblAnaLocalidadAlum.setMaximumSize(new java.awt.Dimension(70, 20));
        lblAnaLocalidadAlum.setMinimumSize(new java.awt.Dimension(70, 20));
        lblAnaLocalidadAlum.setPreferredSize(new java.awt.Dimension(70, 20));

        txtAnaNombreAlum.setMaximumSize(new java.awt.Dimension(150, 25));
        txtAnaNombreAlum.setMinimumSize(new java.awt.Dimension(150, 25));
        txtAnaNombreAlum.setPreferredSize(new java.awt.Dimension(150, 25));

        txtAnaLocalidadAlum.setMaximumSize(new java.awt.Dimension(150, 25));
        txtAnaLocalidadAlum.setMinimumSize(new java.awt.Dimension(150, 25));
        txtAnaLocalidadAlum.setPreferredSize(new java.awt.Dimension(150, 25));

        javax.swing.GroupLayout jpAnadirAlumLayout = new javax.swing.GroupLayout(jpAnadirAlum);
        jpAnadirAlum.setLayout(jpAnadirAlumLayout);
        jpAnadirAlumLayout.setHorizontalGroup(
            jpAnadirAlumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpAnadirAlumLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpAnadirAlumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpAnadirAlumLayout.createSequentialGroup()
                        .addComponent(lblAnaNombreAlum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAnaNombreAlum, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE))
                    .addGroup(jpAnadirAlumLayout.createSequentialGroup()
                        .addComponent(lblAnaLocalidadAlum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAnaLocalidadAlum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jpAnadirAlumLayout.setVerticalGroup(
            jpAnadirAlumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpAnadirAlumLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpAnadirAlumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAnaNombreAlum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAnaNombreAlum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpAnadirAlumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAnaLocalidadAlum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAnaLocalidadAlum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblAltaAlum.setText("ALTA ALUMNOS");
        lblAltaAlum.setMaximumSize(new java.awt.Dimension(120, 30));
        lblAltaAlum.setMinimumSize(new java.awt.Dimension(120, 30));
        lblAltaAlum.setPreferredSize(new java.awt.Dimension(120, 30));

        jScrollPane3.setViewportView(jlAnaModAlum);

        btnAnaModAlum.setText("Añadir");
        btnAnaModAlum.setMaximumSize(new java.awt.Dimension(80, 20));
        btnAnaModAlum.setMinimumSize(new java.awt.Dimension(80, 20));
        btnAnaModAlum.setPreferredSize(new java.awt.Dimension(80, 20));
        btnAnaModAlum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnaModAlumActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jpAnadirAlum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblAltaAlum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(83, 83, 83))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(lblMatricMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jcbModuls, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnQuitarModAlum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAnaModAlum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(btnGrabarAlum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(90, 90, 90)
                        .addComponent(btnLimpiarAlum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(137, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAltaAlum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpAnadirAlum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbModuls, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMatricMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAnaModAlum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(btnQuitarModAlum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnGrabarAlum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimpiarAlum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(118, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jdAnadirAlumLayout = new javax.swing.GroupLayout(jdAnadirAlum.getContentPane());
        jdAnadirAlum.getContentPane().setLayout(jdAnadirAlumLayout);
        jdAnadirAlumLayout.setHorizontalGroup(
            jdAnadirAlumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jdAnadirAlumLayout.setVerticalGroup(
            jdAnadirAlumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jdVerAlum.setTitle("AcademiaMas");
        jdVerAlum.setMaximumSize(new java.awt.Dimension(500, 500));
        jdVerAlum.setMinimumSize(new java.awt.Dimension(500, 500));
        jdVerAlum.setPreferredSize(new java.awt.Dimension(500, 500));

        jPanel3.setMaximumSize(new java.awt.Dimension(500, 500));
        jPanel3.setMinimumSize(new java.awt.Dimension(500, 500));

        lblVerModAlum.setText("Módulos:");
        lblVerModAlum.setMaximumSize(new java.awt.Dimension(70, 20));
        lblVerModAlum.setMinimumSize(new java.awt.Dimension(70, 20));
        lblVerModAlum.setPreferredSize(new java.awt.Dimension(70, 20));

        jpDatosAlum.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 102, 255)), "Datos del alumno", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 0, 255))); // NOI18N
        jpDatosAlum.setToolTipText("");

        lblVerNombreAlum.setText("Nombre:");
        lblVerNombreAlum.setMaximumSize(new java.awt.Dimension(70, 20));
        lblVerNombreAlum.setMinimumSize(new java.awt.Dimension(70, 20));
        lblVerNombreAlum.setPreferredSize(new java.awt.Dimension(70, 20));

        lblVerLocalidadAlum.setText("Localidad:");
        lblVerLocalidadAlum.setMaximumSize(new java.awt.Dimension(70, 20));
        lblVerLocalidadAlum.setMinimumSize(new java.awt.Dimension(70, 20));
        lblVerLocalidadAlum.setPreferredSize(new java.awt.Dimension(70, 20));

        txtVerNombreAlum.setEditable(false);
        txtVerNombreAlum.setMaximumSize(new java.awt.Dimension(150, 25));
        txtVerNombreAlum.setMinimumSize(new java.awt.Dimension(150, 25));
        txtVerNombreAlum.setPreferredSize(new java.awt.Dimension(150, 25));

        txtVerLocalidadAlum.setEditable(false);
        txtVerLocalidadAlum.setMaximumSize(new java.awt.Dimension(150, 25));
        txtVerLocalidadAlum.setMinimumSize(new java.awt.Dimension(150, 25));
        txtVerLocalidadAlum.setPreferredSize(new java.awt.Dimension(150, 25));

        lblVerHorasAlum.setText("Horas:");
        lblVerHorasAlum.setMaximumSize(new java.awt.Dimension(70, 20));
        lblVerHorasAlum.setMinimumSize(new java.awt.Dimension(70, 20));
        lblVerHorasAlum.setPreferredSize(new java.awt.Dimension(70, 20));

        txtVerHorasAlum.setEditable(false);
        txtVerHorasAlum.setMaximumSize(new java.awt.Dimension(150, 25));
        txtVerHorasAlum.setMinimumSize(new java.awt.Dimension(150, 25));
        txtVerHorasAlum.setPreferredSize(new java.awt.Dimension(150, 25));

        javax.swing.GroupLayout jpDatosAlumLayout = new javax.swing.GroupLayout(jpDatosAlum);
        jpDatosAlum.setLayout(jpDatosAlumLayout);
        jpDatosAlumLayout.setHorizontalGroup(
            jpDatosAlumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDatosAlumLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpDatosAlumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpDatosAlumLayout.createSequentialGroup()
                        .addComponent(lblVerNombreAlum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtVerNombreAlum, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE))
                    .addGroup(jpDatosAlumLayout.createSequentialGroup()
                        .addComponent(lblVerLocalidadAlum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtVerLocalidadAlum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpDatosAlumLayout.createSequentialGroup()
                        .addComponent(lblVerHorasAlum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtVerHorasAlum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jpDatosAlumLayout.setVerticalGroup(
            jpDatosAlumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDatosAlumLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpDatosAlumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVerNombreAlum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtVerNombreAlum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpDatosAlumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVerLocalidadAlum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtVerLocalidadAlum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpDatosAlumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVerHorasAlum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtVerHorasAlum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblNombreBuscarAlum.setText("Nombre a buscar:");
        lblNombreBuscarAlum.setMaximumSize(new java.awt.Dimension(120, 20));
        lblNombreBuscarAlum.setMinimumSize(new java.awt.Dimension(120, 20));
        lblNombreBuscarAlum.setPreferredSize(new java.awt.Dimension(120, 20));

        txtNombreAlumBuscar.setMaximumSize(new java.awt.Dimension(150, 25));
        txtNombreAlumBuscar.setMinimumSize(new java.awt.Dimension(150, 25));
        txtNombreAlumBuscar.setPreferredSize(new java.awt.Dimension(150, 25));

        btnMostrarAlum.setText("Mostrar");
        btnMostrarAlum.setMaximumSize(new java.awt.Dimension(80, 20));
        btnMostrarAlum.setMinimumSize(new java.awt.Dimension(80, 20));
        btnMostrarAlum.setPreferredSize(new java.awt.Dimension(80, 20));
        btnMostrarAlum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarAlumActionPerformed(evt);
            }
        });

        jScrollPane4.setViewportView(jlVerModAlum);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lblNombreBuscarAlum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNombreAlumBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lblVerModAlum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4))
                    .addComponent(jpDatosAlum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(btnMostrarAlum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreBuscarAlum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombreAlumBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMostrarAlum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jpDatosAlum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(lblVerModAlum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jdVerAlumLayout = new javax.swing.GroupLayout(jdVerAlum.getContentPane());
        jdVerAlum.getContentPane().setLayout(jdVerAlumLayout);
        jdVerAlumLayout.setHorizontalGroup(
            jdVerAlumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jdVerAlumLayout.setVerticalGroup(
            jdVerAlumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("AcademiaMas");
        setMaximumSize(new java.awt.Dimension(500, 500));
        setMinimumSize(new java.awt.Dimension(500, 500));

        jpPrincipal.setMaximumSize(new java.awt.Dimension(500, 430));
        jpPrincipal.setMinimumSize(new java.awt.Dimension(500, 430));
        jpPrincipal.setPreferredSize(new java.awt.Dimension(500, 430));

        btnAnadirAlum.setText("Añadir Alumno");
        btnAnadirAlum.setMaximumSize(new java.awt.Dimension(120, 30));
        btnAnadirAlum.setMinimumSize(new java.awt.Dimension(120, 30));
        btnAnadirAlum.setPreferredSize(new java.awt.Dimension(120, 30));
        btnAnadirAlum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnadirAlumActionPerformed(evt);
            }
        });

        btnAnadirModul.setText("Añadir Módulo");
        btnAnadirModul.setMaximumSize(new java.awt.Dimension(120, 30));
        btnAnadirModul.setMinimumSize(new java.awt.Dimension(120, 30));
        btnAnadirModul.setPreferredSize(new java.awt.Dimension(120, 30));
        btnAnadirModul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnadirModulActionPerformed(evt);
            }
        });

        btnVerAlum.setText("Ver Alumno");
        btnVerAlum.setMaximumSize(new java.awt.Dimension(120, 30));
        btnVerAlum.setMinimumSize(new java.awt.Dimension(120, 30));
        btnVerAlum.setPreferredSize(new java.awt.Dimension(120, 30));
        btnVerAlum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerAlumActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpPrincipalLayout = new javax.swing.GroupLayout(jpPrincipal);
        jpPrincipal.setLayout(jpPrincipalLayout);
        jpPrincipalLayout.setHorizontalGroup(
            jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPrincipalLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAnadirModul, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVerAlum, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAnadirAlum, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(318, Short.MAX_VALUE))
        );
        jpPrincipalLayout.setVerticalGroup(
            jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPrincipalLayout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(btnAnadirAlum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAnadirModul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnVerAlum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(247, Short.MAX_VALUE))
        );

        jMenuBar1.setMaximumSize(new java.awt.Dimension(500, 70));
        jMenuBar1.setMinimumSize(new java.awt.Dimension(500, 70));
        jMenuBar1.setPreferredSize(new java.awt.Dimension(500, 70));

        jmAlumnos.setText("Alumnos");

        jmiAnadirAlum.setText("Añadir Alumno");
        jmiAnadirAlum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAnadirAlumActionPerformed(evt);
            }
        });
        jmAlumnos.add(jmiAnadirAlum);

        jmiVerAlum.setText("Ver Alumno");
        jmiVerAlum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiVerAlumActionPerformed(evt);
            }
        });
        jmAlumnos.add(jmiVerAlum);

        jmiGuardarAlum.setText("Guardar Alumno");
        jmiGuardarAlum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiGuardarAlumActionPerformed(evt);
            }
        });
        jmAlumnos.add(jmiGuardarAlum);

        jmiSalvarAlum.setText("Salvar Alumno");
        jmiSalvarAlum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiSalvarAlumActionPerformed(evt);
            }
        });
        jmAlumnos.add(jmiSalvarAlum);

        jMenuBar1.add(jmAlumnos);

        jmModulos.setText("Módulos");

        jmiAnadirModul.setText("Añadir Módulo");
        jmiAnadirModul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAnadirModulActionPerformed(evt);
            }
        });
        jmModulos.add(jmiAnadirModul);

        jmiGuardarModul.setText("Guardar Módulo");
        jmiGuardarModul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiGuardarModulActionPerformed(evt);
            }
        });
        jmModulos.add(jmiGuardarModul);

        jmiSalvarModul.setText("Salvar Módulo");
        jmiSalvarModul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiSalvarModulActionPerformed(evt);
            }
        });
        jmModulos.add(jmiSalvarModul);

        jMenuBar1.add(jmModulos);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAnadirModulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnadirModulActionPerformed
        // TODO add your handling code here:
        jdAnadirModul.setVisible(true);
    }//GEN-LAST:event_btnAnadirModulActionPerformed

    private void btnAnadirAlumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnadirAlumActionPerformed
        // TODO add your handling code here:
        jdAnadirAlum.setVisible(true);
        cargarModulosDisponibles();
    }//GEN-LAST:event_btnAnadirAlumActionPerformed

    private void btnVerAlumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerAlumActionPerformed
        // TODO add your handling code here:
        jdVerAlum.setVisible(true);
    }//GEN-LAST:event_btnVerAlumActionPerformed

    private void jmiAnadirAlumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAnadirAlumActionPerformed
        // TODO add your handling code here:
        jdAnadirAlum.setVisible(true);
    }//GEN-LAST:event_jmiAnadirAlumActionPerformed

    private void jmiVerAlumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiVerAlumActionPerformed
        // TODO add your handling code here:
        jdVerAlum.setVisible(true);
    }//GEN-LAST:event_jmiVerAlumActionPerformed

    private void jmiGuardarAlumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiGuardarAlumActionPerformed
        // TODO add your handling code here:
        guardarAlumnosTxt();
    }//GEN-LAST:event_jmiGuardarAlumActionPerformed

    private void jmiSalvarAlumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiSalvarAlumActionPerformed
        // TODO add your handling code here:
        cargarAlumnosTxt();
    }//GEN-LAST:event_jmiSalvarAlumActionPerformed

    private void jmiAnadirModulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAnadirModulActionPerformed
        // TODO add your handling code here:
        jdAnadirModul.setVisible(true);
    }//GEN-LAST:event_jmiAnadirModulActionPerformed

    private void jmiGuardarModulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiGuardarModulActionPerformed
        // TODO add your handling code here:
        guardarModulosTxt();
    }//GEN-LAST:event_jmiGuardarModulActionPerformed

    private void jmiSalvarModulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiSalvarModulActionPerformed
        // TODO add your handling code here:
        cargarModulosTxt();
    }//GEN-LAST:event_jmiSalvarModulActionPerformed

    
    
    //FICHEROS//
    
    private void inicializarOutputGuardar(File f) throws IOException {
        outGuardar=new ObjectOutputStream(new FileOutputStream(f));
    }
    
    private void inicializarInputCargar(File f) throws IOException {
        inCargar=new ObjectInputStream(new FileInputStream(f));
    }
    
    private void guardarAlumnosTxt(){
        try {
            inicializarOutputGuardar(txtAlumnos);
            outGuardar.writeObject(listaAlumnos);
            outGuardar.close();
            JOptionPane.showMessageDialog(this, "Alumnos guardados correctamente.");
        }catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Error al guardar Alumnos.");
        }
    }
    
    private void cargarAlumnosTxt(){
        try{
            inicializarInputCargar(txtAlumnos);
            listaAlumnos=(ArrayList)inCargar.readObject();
            JOptionPane.showMessageDialog(this, "Alumnos cargados correctamente.");
        }catch (Exception e){
            JOptionPane.showMessageDialog(this, "Error al cargar Alumnos.");
        }
    }
    
    private void guardarModulosTxt(){
        try {
            inicializarOutputGuardar(txtModulos);
            outGuardar.writeObject(listaModulos);
            outGuardar.close();
            JOptionPane.showMessageDialog(this, "Módulos guardados correctamente.");
        }catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Error al guardar Módulos.");
        }
    }
    
    private void cargarModulosTxt(){
        try{
            inicializarInputCargar(txtModulos);
            listaModulos=(ArrayList)inCargar.readObject();
            JOptionPane.showMessageDialog(this, "Módulos cargados correctamente.");
        }catch (Exception e){
            JOptionPane.showMessageDialog(this, "Error al cargar Módulos.");
        }
    }

    
    
    //DIALOG AÑADIR MODULO//
    
    private void crearModulo(){
        try{
            String nombreMod = txtNombreMod.getText();
            int horasMod = Integer.parseInt(txtHorasMod.getText());
            int unidadesMod = Integer.parseInt(txtUnidadesMod.getText());
            if (nombreMod.length()<2){
                JOptionPane.showMessageDialog(this, "El módulo tiene que tener un nombre de 2 carácteres o más.");
            }
            else{
                Modulo modul = new Modulo(nombreMod, horasMod, unidadesMod);
                anadirModulo(modul);
            }
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "El módulo no se pudo añadir.");
        }
    }
    
    private void limpiarAltaMod(){
        txtNombreMod.setText("");
        txtHorasMod.setText("");
        txtUnidadesMod.setText("");
    }
    
    private void btnGrabarModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrabarModActionPerformed
        // TODO add your handling code here:
        crearModulo();
        limpiarAltaMod();
    }//GEN-LAST:event_btnGrabarModActionPerformed

    private void btnLimpiarModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarModActionPerformed
        // TODO add your handling code here:
        limpiarAltaMod();
    }//GEN-LAST:event_btnLimpiarModActionPerformed

    
    
    //DIALOG AÑADIR ALUMNO//
    
    private void crearAlum(){
        String nombreAlum = txtAnaNombreAlum.getText();
        String localidadAlum = txtAnaLocalidadAlum.getText();
        if (nombreAlum.length()<2 || localidadAlum.length()<2){
            JOptionPane.showMessageDialog(this, "El alumno y la localidad tienen que tener un nombre de 2 carácteres o más.");
        }
        else{
            Alumno alum = null;
            if (jlAnaModAlum.getModel().getSize()==0){
                alum = new Alumno(nombreAlum, localidadAlum);
                anadirAlumno(alum);
            }
            else{
                ArrayList<Modulo> modulos = new ArrayList();
                int horas=0;
                for (int i = 0; i < jlAnaModAlum.getModel().getSize(); i++) {
                    String nomeMod = jlAnaModAlum.getModel().getElementAt(i);
                    Modulo mod = obterModulo(nomeMod);
                    modulos.add(mod);
                    horas+=mod.getHoras();
                }
                if (horas>30){
                    JOptionPane.showMessageDialog(this, "El total de horas cursadas no puede exceder las 30.");
                }
                else{
                    alum = new Alumno(nombreAlum, localidadAlum, modulos);
                    anadirAlumno(alum);
                }
            }
        }
        //JOptionPane.showMessageDialog(this, "El alumno no se pudo añadir.");
    }
    
    private void limpiarAltaAlum(){
        txtAnaNombreAlum.setText("");
        txtAnaLocalidadAlum.setText("");
        modelListaModAlum.removeAllElements();
        jlAnaModAlum.setModel(modelListaModAlum);
        cargarModulosDisponibles();
    }
    
    private void cargarModulosDisponibles(){
        jcbModuls.removeAllItems();
        for (int i = 0; i < listaModulos.size(); i++) {
            jcbModuls.addItem(listaModulos.get(i).getNombre());
        }
    }
    
    private void btnGrabarAlumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrabarAlumActionPerformed
        // TODO add your handling code here:
        crearAlum();
        limpiarAltaAlum();
    }//GEN-LAST:event_btnGrabarAlumActionPerformed

    private void btnLimpiarAlumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarAlumActionPerformed
        // TODO add your handling code here:
        limpiarAltaAlum();
    }//GEN-LAST:event_btnLimpiarAlumActionPerformed

    private void btnQuitarModAlumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitarModAlumActionPerformed
        // TODO add your handling code here:
        if(jlAnaModAlum.getSelectedValue()!=null){
            jcbModuls.addItem(jlAnaModAlum.getSelectedValue());
            modelListaModAlum.remove(jlAnaModAlum.getSelectedIndex());
            jlAnaModAlum.setModel(modelListaModAlum);
        }
    }//GEN-LAST:event_btnQuitarModAlumActionPerformed

    private void jcbModulsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbModulsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbModulsActionPerformed

    private void btnAnaModAlumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnaModAlumActionPerformed
        // TODO add your handling code here:
        if (jcbModuls.getSelectedItem()!=null){
            modelListaModAlum.addElement(jcbModuls.getSelectedItem());
            jcbModuls.removeItem(jcbModuls.getSelectedItem());
            jlAnaModAlum.setModel(modelListaModAlum);
        }
    }//GEN-LAST:event_btnAnaModAlumActionPerformed

    
    
    //DIALOG VER ALUMNO//
    
    private void btnMostrarAlumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarAlumActionPerformed
        // TODO add your handling code here:
        Alumno alum = obterAlumno(txtNombreAlumBuscar.getText());
        if (alum!=null){
            txtVerNombreAlum.setText(alum.getNombre());
            txtVerLocalidadAlum.setText(alum.getLocalidad());
            txtVerHorasAlum.setText(alum.getNumeroHoras()+"");
            
            jlVerModAlum.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = alum.getNombreModulos();
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
            });
        }
        else{
            txtVerNombreAlum.setText("");
            txtVerLocalidadAlum.setText("");
            txtVerHorasAlum.setText("");
            jlVerModAlum.setModel(new DefaultListModel());
            JOptionPane.showMessageDialog(this, "Alumno no encontrado.");
        }
    }//GEN-LAST:event_btnMostrarAlumActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }
    
    private void anadirAlumno(Alumno alum){
        listaAlumnos.add(alum);
    }
    
    private void anadirModulo(Modulo modul){
        listaModulos.add(modul);
    }
    
    private Alumno obterAlumno(String nome){
        Alumno alumBuscado = null;
        boolean encontrado=false;
        for (int i = 0; i < listaAlumnos.size() && !encontrado; i++) {
            if(listaAlumnos.get(i).getNombre().equals(nome)){
                alumBuscado=listaAlumnos.get(i);
                encontrado=true;
            }
        }
        return alumBuscado;
    }
    
    private Modulo obterModulo(String nome){
        Modulo modBuscado = null;
        boolean encontrado=false;
        for (int i = 0; i < listaModulos.size() && !encontrado; i++) {
            if(listaModulos.get(i).getNombre()==nome){
                modBuscado=listaModulos.get(i);
                encontrado=true;
            }
        }
        return modBuscado;
    }
    
    private int obterTamanoListaAlumnos(){
        return listaAlumnos.size();
    }
    
    private int obterTamanoListaModulos(){
        return listaModulos.size();
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnaModAlum;
    private javax.swing.JButton btnAnadirAlum;
    private javax.swing.JButton btnAnadirModul;
    private javax.swing.JButton btnGrabarAlum;
    private javax.swing.JButton btnGrabarMod;
    private javax.swing.JButton btnLimpiarAlum;
    private javax.swing.JButton btnLimpiarMod;
    private javax.swing.JButton btnMostrarAlum;
    private javax.swing.JButton btnQuitarModAlum;
    private javax.swing.JButton btnVerAlum;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JComboBox<String> jcbModuls;
    private javax.swing.JDialog jdAnadirAlum;
    private javax.swing.JDialog jdAnadirModul;
    private javax.swing.JDialog jdVerAlum;
    private javax.swing.JList<String> jlAnaModAlum;
    private javax.swing.JList<String> jlVerModAlum;
    private javax.swing.JMenu jmAlumnos;
    private javax.swing.JMenu jmModulos;
    private javax.swing.JMenuItem jmiAnadirAlum;
    private javax.swing.JMenuItem jmiAnadirModul;
    private javax.swing.JMenuItem jmiGuardarAlum;
    private javax.swing.JMenuItem jmiGuardarModul;
    private javax.swing.JMenuItem jmiSalvarAlum;
    private javax.swing.JMenuItem jmiSalvarModul;
    private javax.swing.JMenuItem jmiVerAlum;
    private javax.swing.JPanel jpAnadirAlum;
    private javax.swing.JPanel jpAnadirMod;
    private javax.swing.JPanel jpDatosAlum;
    private javax.swing.JPanel jpPrincipal;
    private javax.swing.JLabel lblAltaAlum;
    private javax.swing.JLabel lblAltaModul;
    private javax.swing.JLabel lblAnaLocalidadAlum;
    private javax.swing.JLabel lblAnaNombreAlum;
    private javax.swing.JLabel lblHorasMod;
    private javax.swing.JLabel lblMatricMod;
    private javax.swing.JLabel lblNombreBuscarAlum;
    private javax.swing.JLabel lblNombreMod;
    private javax.swing.JLabel lblUnidadesMod;
    private javax.swing.JLabel lblVerHorasAlum;
    private javax.swing.JLabel lblVerLocalidadAlum;
    private javax.swing.JLabel lblVerModAlum;
    private javax.swing.JLabel lblVerNombreAlum;
    private javax.swing.JTextField txtAnaLocalidadAlum;
    private javax.swing.JTextField txtAnaNombreAlum;
    private javax.swing.JTextField txtHorasMod;
    private javax.swing.JTextField txtNombreAlumBuscar;
    private javax.swing.JTextField txtNombreMod;
    private javax.swing.JTextField txtUnidadesMod;
    private javax.swing.JTextField txtVerHorasAlum;
    private javax.swing.JTextField txtVerLocalidadAlum;
    private javax.swing.JTextField txtVerNombreAlum;
    // End of variables declaration//GEN-END:variables
}
